[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "B", "UP", "SIM", "PERF"]
ignore = [
    "E501",  # line too long
    "UP047", # pyupgrade
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
